// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa8KfGnWIx4s6AIkcMw33GmwOO43RdKfs',
    appId: '1:293076145285:web:13f87dcaf5c0c28b3545ec',
    messagingSenderId: '293076145285',
    projectId: 'bdtcc-e0559',
    authDomain: 'bdtcc-e0559.firebaseapp.com',
    storageBucket: 'bdtcc-e0559.appspot.com',
    measurementId: 'G-F4CPB112XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZA7vx0aFosAGg-YAolAKKnk4_NornOdU',
    appId: '1:293076145285:android:f499d48f54fe675c3545ec',
    messagingSenderId: '293076145285',
    projectId: 'bdtcc-e0559',
    storageBucket: 'bdtcc-e0559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAQCv6zSMIW21QqiuWkuMmHqLEoeS0-TI',
    appId: '1:293076145285:ios:ea2c931a48b367373545ec',
    messagingSenderId: '293076145285',
    projectId: 'bdtcc-e0559',
    storageBucket: 'bdtcc-e0559.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
